[2025-09-09T18:50:29.684+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-09T18:50:29.715+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pl_mlops.create_insert_data manual__2025-09-09T18:50:20.537959+00:00 [queued]>
[2025-09-09T18:50:29.723+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pl_mlops.create_insert_data manual__2025-09-09T18:50:20.537959+00:00 [queued]>
[2025-09-09T18:50:29.724+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2025-09-09T18:50:29.734+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): create_insert_data> on 2025-09-09 18:50:20.537959+00:00
[2025-09-09T18:50:29.743+0000] {standard_task_runner.py:72} INFO - Started process 3762 to run task
[2025-09-09T18:50:29.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pl_mlops', 'create_insert_data', 'manual__2025-09-09T18:50:20.537959+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/mlops_pl.py', '--cfg-path', '/tmp/tmp1cy_sd14']
[2025-09-09T18:50:29.750+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask create_insert_data
[2025-09-09T18:50:29.855+0000] {task_command.py:467} INFO - Running <TaskInstance: pl_mlops.create_insert_data manual__2025-09-09T18:50:20.537959+00:00 [running]> on host 217056bd8467
[2025-09-09T18:50:30.006+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khuong' AIRFLOW_CTX_DAG_ID='pl_mlops' AIRFLOW_CTX_TASK_ID='create_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T18:50:20.537959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T18:50:20.537959+00:00'
[2025-09-09T18:50:30.008+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-09T18:50:30.010+0000] {logging_mixin.py:190} INFO - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbGFwaGFtMTI0N0BnbWFpbC5jb20iLCJzZXNzaW9uIjoiaG9sYXBoYW0xMjQ3LmdtYWlsLmNvbSIsInBhdCI6IkJyOG1RNzBmbXZ6aml2QlJ4eTRwaWliUTZ5Umc1eHpTZHdtMzZmek9zRjgiLCJ1c2VySWQiOiIzMTBhZjI1ZC05ZjVmLTRlMWUtOTAwMi1iMDk1M2ZmMGM0MDAiLCJpc3MiOiJtZF9wYXQiLCJyZWFkT25seSI6ZmFsc2UsInRva2VuVHlwZSI6InJlYWRfd3JpdGUiLCJpYXQiOjE3NTQ4NDEyOTQsImV4cCI6MTc4NjM3NzI5NH0.CNI8DuyqAKxLaIItowF_mmN4JWW_ZXz63xTa5w9l7zg
[2025-09-09T18:53:32.985+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-09T18:53:32.987+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-09-09T18:53:32.988+0000] {process_utils.py:132} INFO - Sending 15 to group 3762. PIDs of all processes in the group: [3762]
[2025-09-09T18:53:32.989+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3762
[2025-09-09T18:54:33.003+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=3762, name='airflow task ru', status='sleeping', started='18:50:29') did not respond to SIGTERM. Trying SIGKILL
[2025-09-09T18:54:33.005+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 3762
[2025-09-09T18:54:33.019+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3762, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='18:50:29') (3762) terminated with exit code -9
[2025-09-09T18:54:33.021+0000] {standard_task_runner.py:190} ERROR - ('Job 11 was killed before it finished (likely due to running out of memory)', 'For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed')
