[2025-09-14T14:10:35.253+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-14T14:10:35.288+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_mlops_pl_full_load.create_insert_data manual__2025-09-14T14:10:15.501560+00:00 [queued]>
[2025-09-14T14:10:35.297+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_mlops_pl_full_load.create_insert_data manual__2025-09-14T14:10:15.501560+00:00 [queued]>
[2025-09-14T14:10:35.298+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2025-09-14T14:10:35.310+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): create_insert_data> on 2025-09-14 14:10:15.501560+00:00
[2025-09-14T14:10:35.320+0000] {standard_task_runner.py:72} INFO - Started process 20489 to run task
[2025-09-14T14:10:35.323+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_mlops_pl_full_load', 'create_insert_data', 'manual__2025-09-14T14:10:15.501560+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/stock_pl_full_load.py', '--cfg-path', '/tmp/tmp31wpq0um']
[2025-09-14T14:10:35.325+0000] {standard_task_runner.py:105} INFO - Job 335: Subtask create_insert_data
[2025-09-14T14:10:35.438+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_mlops_pl_full_load.create_insert_data manual__2025-09-14T14:10:15.501560+00:00 [running]> on host 7c4a8787553d
[2025-09-14T14:10:35.577+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khuong' AIRFLOW_CTX_DAG_ID='stock_mlops_pl_full_load' AIRFLOW_CTX_TASK_ID='create_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-14T14:10:15.501560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-14T14:10:15.501560+00:00'
[2025-09-14T14:10:35.578+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-14T14:10:37.456+0000] {logging_mixin.py:190} INFO - Connect DuckDB Successfully!
[2025-09-14T14:11:34.029+0000] {logging_mixin.py:190} INFO - Catalog Error: Table with name BINANCE does not exist!
Did you mean "EXCHANGE_RATE"?
[2025-09-14T14:11:34.030+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-09-14T14:11:34.054+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-14T14:11:34.054+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_mlops_pl_full_load, task_id=create_insert_data, run_id=manual__2025-09-14T14:10:15.501560+00:00, execution_date=20250914T141015, start_date=20250914T141035, end_date=20250914T141134
[2025-09-14T14:11:34.110+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-09-14T14:11:34.138+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-14T14:11:34.141+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
