[2025-09-13T20:18:06.933+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-13T20:18:06.943+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_mlops_pl.create_insert_data manual__2025-09-13T20:18:02.067858+00:00 [queued]>
[2025-09-13T20:18:06.950+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_mlops_pl.create_insert_data manual__2025-09-13T20:18:02.067858+00:00 [queued]>
[2025-09-13T20:18:06.951+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2025-09-13T20:18:06.956+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): create_insert_data> on 2025-09-13 20:18:02.067858+00:00
[2025-09-13T20:18:06.960+0000] {standard_task_runner.py:72} INFO - Started process 4259 to run task
[2025-09-13T20:18:06.963+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_mlops_pl', 'create_insert_data', 'manual__2025-09-13T20:18:02.067858+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/stock_mlops_pl.py', '--cfg-path', '/tmp/tmp6kgdq2z1']
[2025-09-13T20:18:06.964+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask create_insert_data
[2025-09-13T20:18:06.995+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_mlops_pl.create_insert_data manual__2025-09-13T20:18:02.067858+00:00 [running]> on host f56d726d67de
[2025-09-13T20:18:07.040+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khuong' AIRFLOW_CTX_DAG_ID='stock_mlops_pl' AIRFLOW_CTX_TASK_ID='create_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T20:18:02.067858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T20:18:02.067858+00:00'
[2025-09-13T20:18:07.042+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-13T20:18:08.835+0000] {logging_mixin.py:190} INFO - Connect DuckDB Successfully!
[2025-09-13T20:18:09.875+0000] {logging_mixin.py:190} INFO - Parser Error: syntax error at or near "["
[2025-09-13T20:18:09.877+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-09-13T20:18:09.895+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-13T20:18:09.896+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_mlops_pl, task_id=create_insert_data, run_id=manual__2025-09-13T20:18:02.067858+00:00, execution_date=20250913T201802, start_date=20250913T201806, end_date=20250913T201809
[2025-09-13T20:18:09.930+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-09-13T20:18:09.950+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T20:18:09.951+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
